version: '3.8'

services:
  db:
    image: postgres:15
    container_name: myauth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth
    ports:
      - "5429:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-network

  zookeeper_auth:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper_auth
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - spring-network

  kafka_auth:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_auth
    depends_on:
      - zookeeper_auth
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_auth:2181
      # Listeners configuration
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_auth:29092,EXTERNAL://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # Reliability & Auto-creation
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - spring-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka_auth
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      # UI uses the INTERNAL network to talk to Kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka_auth:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  pgdata: