server.port=8081
spring.application.name=my-kafka-example

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#KAFKA
spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.kafka.consumer.group-id=myauth
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.topic.name=example.send.message.topic
spring.kafka.consumer.properties.spring.json.trusted.packages=*

#DB
spring.datasource.url=jdbc:postgresql://localhost:5429/auth 
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

#AUTH
auth.base.url=http://localhost:8080

